### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by jt387** [JinpengLI/deep_ocr#37]
你好， 按照步骤配置好虚拟环境后， 执行如下：
haiyun@dell-Precision-Tower-5810:~$ source ~/deep_ocr_env/bin/activate && cd ~/deep_ocr && ./bin/deep_ocr_reco data/holiday_notification.jpg -v -d
! image to reco: data/holiday_notification.jpg
Traceback (most recent call last):
  File "./bin/deep_ocr_reco", line 137, in <module>
    show_img(raw, title="raw image")
  File "./bin/deep_ocr_reco", line 27, in show_img
    plt.gray()
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3932, in gray
    set_cmap("gray")
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2372, in set_cmap
    im = gci()
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 335, in gci
    return gcf()._gci()
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 601, in gcf
    return figure()
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/haiyun/deep_ocr_env/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1044, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/haiyun/install/python-2.7.11/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0"
 在网上搜索“_tkinter.TclError: couldn't connect to display ":0"” 尝试去解决没有成功， 烦请指点! 多谢！

**Comment by nickel823** [comment]
sudo apt-get install python-tk
