### ISSUE TITLE
Could not open file /workspace/data/chongdata_caffe_cn_sim_digits_64_64/deploy_lenet_train_test.prototxt

### ISSUE THREAD

**Issue by LuWei6896** [JinpengLI/deep_ocr#41]
我仔细检查了每个依赖库、模型文件路径、解压等因素，还是报这个错误？所以，是你上传的压缩文件错误吗？
Traceback (most recent call last):
  File "reco_chars.py", line 294, in <module>
    caffe_cls = CaffeCls(model_def, model_weights, y_tag_json_path)
  File "reco_chars.py", line 20, in __init__
    caffe.TEST)
RuntimeError: Could not open file /workspace/data/chongdata_caffe_cn_sim_digits_64_64/deploy_lenet_train_test.prototx

best regards!

**Comment by LuWei6896** [comment]
> 我仔细检查了每个依赖库、模型文件路径、解压等因素，还是报这个错误？所以，是你上传的压缩文件错误吗？
> Traceback (most recent call last):
> File "reco_chars.py", line 294, in
> caffe_cls = CaffeCls(model_def, model_weights, y_tag_json_path)
> File "reco_chars.py", line 20, in **init**
> caffe.TEST)
> RuntimeError: Could not open file /workspace/data/chongdata_caffe_cn_sim_digits_64_64/deploy_lenet_train_test.prototx
> 
> best regards!
