### ISSUE TITLE
RuntimeError: Could not open file

### ISSUE THREAD

**Issue by 984958198** [JinpengLI/deep_ocr#9]
我下载了deep_ocr_workspace.zip 和  reco_chars.py  运行脚本出现以下错误，而且你的压缩包在window下解压出错。 我感觉是你的压缩文件有问题

root@orange-VirtualBox:~/caffe/python# python reco_chars.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1223 17:24:19.496032  3764 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W1223 17:24:19.496183  3764 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W1223 17:24:19.496206  3764 _caffe.cpp:125] Net('/workspace/data/chongdata_caffe_cn_sim_digits_64_64/deploy_lenet_train_test.prototxt', 1, weights='/workspace/data/chongdata_caffe_cn_sim_digits_64_64/lenet_iter_50000.caffemodel')
Traceback (most recent call last):
  File "test.py", line 294, in <module>
    caffe_cls = CaffeCls(model_def, model_weights, y_tag_json_path)
  File "test.py", line 20, in __init__
    caffe.TEST)
RuntimeError: Could not open file /workspace/data/chongdata_caffe_cn_sim_digits_64_64/lenet_iter_50000.caffemodel

**Comment by xjdata** [comment]
+1

**Comment by JinpengLI** [comment]
刚刚测试了一下，确实有这个问题，重新上传两个压缩文件，现在应该可以用

**Comment by xjdata** [comment]
@JinpengLI  请问新上传的地址还是百度的吗?  还是其他的新的地址呢?

**Comment by xjdata** [comment]
呃.... 看到你百度账户的分享了,1.8号有新文件.我去测试下,谢谢.

**Comment by xjdata** [comment]
郁闷,,,是不是我人品问题.... 还是不行. 删除重新下了2次,都一样.......

```
➜  Downloads unzip deep_ocr_workspace.zip 
Archive:  deep_ocr_workspace.zip
warning [deep_ocr_workspace.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4
file #2:  bad zipfile offset (local header sig):  81
file #3:  bad zipfile offset (local header sig):  163
file #4:  bad zipfile offset (local header sig):  281
file #5:  bad zipfile offset (lseek):  553009152
file #6:  bad zipfile offset (lseek):  553041920
file #7:  bad zipfile offset (lseek):  553050112
file #8:  bad zipfile offset (EOF):  553051325
file #9:  bad zipfile offset (EOF):  553054733
  inflating: deep_ocr_workspace/data/chongdata_caffe_cn_sim_digits_64_64/train_lenet.sh  
  inflating: deep_ocr_workspace/data/chongdata_caffe_cn_sim_digits_64_64/y_tag.label  
  inflating: deep_ocr_workspace/data/chongdata_caffe_cn_sim_digits_64_64/lenet.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_caffe_cn_sim_digits_64_64/model_def.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_caffe_cn_sim_digits_64_64/deploy_lenet_train_test.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_caffe_cn_sim_digits_64_64/y_tag.txt  
   creating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/lenet_iter_50000.caffemodel  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/train_caffenet.sh  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/create_imagenet.sh  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/y_tag.json  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/lenet_train_test.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/lenet_solver.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/readme.md  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/make_imagenet_mean.sh  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/model_weights.caffemodel  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/train_lenet.sh  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/y_tag.label  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/resume_training.sh  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/lenet.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/lenet_iter_50000.solverstate  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/model_def.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/deploy_lenet_train_test.prototxt  
  inflating: deep_ocr_workspace/data/chongdata_train_ualpha_digits_64_64/y_tag.txt
```

**Comment by JinpengLI** [comment]
看上去你漏了合并两个zip文件，linux下面的unzip不会自动合并文件，见项目主页的如何合并。

```
cat deep_ocr_workspace.z* > unsplit_deep_ocr_workspace.zip
unzip unsplit_deep_ocr_workspace.zip -d ~/
```

**Comment by xjdata** [comment]
呃.... 不好意思. 谢谢!

**Comment by 984958198** [comment]
我在http://chongdata.com/ocr/上找到这个框架，我以为识别效果和它一样，结果测试了下 彩色的图片识别不出，是我参数没调好吗？ 比如如下图
![0](https://cloud.githubusercontent.com/assets/9883283/21876039/0eae5cba-d8bb-11e6-9b57-67f4914d9f23.jpg)

**Comment by JinpengLI** [comment]
不支持。这种案例暂时太复杂了。。跟参数没关系。。
